[aws]
symbol = " "

[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[directory]
prefix = ""
disabled = false

[character]
symbol = "❯"
error_symbol = "✖"
use_symbol_for_status = true

[username]
disabled = true
show_always = true

[hostname]
ssh_only = false
prefix = "⟪"
suffix = "⟫"
disabled = true

[conda]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "